name: ci

on:
  push:
    tags-ignore:
      - 'v*.*.*'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: notomo/action-setup-nvim-lua@v1
      - run: luarocks install vusted

      - run: make new_rockspec VERSION=0.0.0

      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - run: make test
        env:
          VUSTED_NVIM: ${{ steps.vim.outputs.executable }}
